[package]
name = "duck-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duck-bytecode = {path = "../duck-bytecode"}
duck-vm = {path = "../duck-vm"}
